/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReaderRouteImport } from './routes/reader'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FeedFeedUuidRouteImport } from './routes/feed/$feedUuid'

const ReaderRoute = ReaderRouteImport.update({
  id: '/reader',
  path: '/reader',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedFeedUuidRoute = FeedFeedUuidRouteImport.update({
  id: '/feed/$feedUuid',
  path: '/feed/$feedUuid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reader': typeof ReaderRoute
  '/feed/$feedUuid': typeof FeedFeedUuidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reader': typeof ReaderRoute
  '/feed/$feedUuid': typeof FeedFeedUuidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reader': typeof ReaderRoute
  '/feed/$feedUuid': typeof FeedFeedUuidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/reader' | '/feed/$feedUuid'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/reader' | '/feed/$feedUuid'
  id: '__root__' | '/' | '/reader' | '/feed/$feedUuid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReaderRoute: typeof ReaderRoute
  FeedFeedUuidRoute: typeof FeedFeedUuidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reader': {
      id: '/reader'
      path: '/reader'
      fullPath: '/reader'
      preLoaderRoute: typeof ReaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/$feedUuid': {
      id: '/feed/$feedUuid'
      path: '/feed/$feedUuid'
      fullPath: '/feed/$feedUuid'
      preLoaderRoute: typeof FeedFeedUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReaderRoute: ReaderRoute,
  FeedFeedUuidRoute: FeedFeedUuidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
