/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminFeedsRouteImport } from './routes/admin.feeds'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AppReaderRouteImport } from './routes/_app.reader'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppFeedFeedIdRouteImport } from './routes/_app.feed.$feedId'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeedsRoute = AdminFeedsRouteImport.update({
  id: '/feeds',
  path: '/feeds',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AppReaderRoute = AppReaderRouteImport.update({
  id: '/reader',
  path: '/reader',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedFeedIdRoute = AppFeedFeedIdRouteImport.update({
  id: '/feed/$feedId',
  path: '/feed/$feedId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/profile': typeof AppProfileRoute
  '/reader': typeof AppReaderRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/feeds': typeof AdminFeedsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/feed/$feedId': typeof AppFeedFeedIdRoute
}
export interface FileRoutesByTo {
  '/profile': typeof AppProfileRoute
  '/reader': typeof AppReaderRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/feeds': typeof AdminFeedsRoute
  '/admin/users': typeof AdminUsersRoute
  '/': typeof AppIndexRoute
  '/admin': typeof AdminIndexRoute
  '/feed/$feedId': typeof AppFeedFeedIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_app/profile': typeof AppProfileRoute
  '/_app/reader': typeof AppReaderRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/feeds': typeof AdminFeedsRoute
  '/admin/users': typeof AdminUsersRoute
  '/_app/': typeof AppIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_app/feed/$feedId': typeof AppFeedFeedIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/profile'
    | '/reader'
    | '/admin/categories'
    | '/admin/feeds'
    | '/admin/users'
    | '/admin/'
    | '/feed/$feedId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/profile'
    | '/reader'
    | '/admin/categories'
    | '/admin/feeds'
    | '/admin/users'
    | '/'
    | '/admin'
    | '/feed/$feedId'
  id:
    | '__root__'
    | '/_app'
    | '/admin'
    | '/_app/profile'
    | '/_app/reader'
    | '/admin/categories'
    | '/admin/feeds'
    | '/admin/users'
    | '/_app/'
    | '/admin/'
    | '/_app/feed/$feedId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/feeds': {
      id: '/admin/feeds'
      path: '/feeds'
      fullPath: '/admin/feeds'
      preLoaderRoute: typeof AdminFeedsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/reader': {
      id: '/_app/reader'
      path: '/reader'
      fullPath: '/reader'
      preLoaderRoute: typeof AppReaderRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feed/$feedId': {
      id: '/_app/feed/$feedId'
      path: '/feed/$feedId'
      fullPath: '/feed/$feedId'
      preLoaderRoute: typeof AppFeedFeedIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppProfileRoute: typeof AppProfileRoute
  AppReaderRoute: typeof AppReaderRoute
  AppIndexRoute: typeof AppIndexRoute
  AppFeedFeedIdRoute: typeof AppFeedFeedIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProfileRoute: AppProfileRoute,
  AppReaderRoute: AppReaderRoute,
  AppIndexRoute: AppIndexRoute,
  AppFeedFeedIdRoute: AppFeedFeedIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminFeedsRoute: typeof AdminFeedsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminFeedsRoute: AdminFeedsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
