[package]
name = "redy"
version = "0.1.0"
edition = "2024"

[dependencies]
utoipa = { version = "5", features = ["axum_extras", "chrono", "uuid"] }
utoipa-axum = "0.2"
utoipa-swagger-ui = { version = "9", features = ["axum"] }
legible = "0.4.2"
readabilityrs = "0.1.2"
reqwest = "0.13.2"
tokio = { version = "1.50.0", features = ["full"] }
chromiumoxide = "0.9.1"
axum = { version = "0.8", features = ["json"] }
axum-oidc = { git = "https://codeberg.org/pfzetto/axum-oidc", rev = "f698c462" }
tower-sessions = "0.14"
tower-sessions-redis-store = "0.16"
tower = "0.4"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0.102"
lazy_static = "1.5.0"
thiserror = "2.0.18"
sea-orm = { version = "1.1.0", features = [
    "sqlx-postgres",
    "runtime-tokio-native-tls",
    "macros",
    "with-uuid",
] }
futures = "0.3.32"
uuid = { version = "1.22.0", features = ["v4"] }
tower-http = { version = "0.6.8", features = ["cors"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
rss = "2.0"
chrono = { version = "0.4.44", features = ["serde"] }
sha2 = "0.11.0"
async-nats = { version = "0.47.0", features = ["jetstream", "websockets"] }
tokio-stream = "0.1.18"
migration = { path = "../migration"}
tracing-log = "0.2"
clap = { version = "4.6.0", features = ["derive"] }
openidconnect = { version = "4.0.1", features = ["reqwest"] }
dotenv = { version = "0.15.0", optional = true }
metrics = "0.24.3"
metrics-exporter-prometheus = "0.18.1"
ammonia = "4.1.2"

[features]
dotenv = ["dep:dotenv"]
