//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::ArticleStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "article")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub feed_id: Uuid,
    pub title: String,
    pub feed_description: Option<String>,
    #[sea_orm(unique)]
    pub content_hash: String,
    pub link: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub html_content: Option<String>,
    pub status: ArticleStatus,
    pub published_at: Option<DateTimeWithTimeZone>,
    pub fetched_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::article_data::Entity")]
    ArticleData,
    #[sea_orm(
        belongs_to = "super::feed::Entity",
        from = "Column::FeedId",
        to = "super::feed::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Feed,
}

impl Related<super::article_data::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArticleData.def()
    }
}

impl Related<super::feed::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Feed.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
