//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "category")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub human_name: String,
    pub model_description: String,
    pub human_description: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::article_data::Entity")]
    ArticleData,
    #[sea_orm(has_many = "super::feed_category::Entity")]
    FeedCategory,
}

impl Related<super::article_data::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArticleData.def()
    }
}

impl Related<super::feed_category::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FeedCategory.def()
    }
}

impl Related<super::feed::Entity> for Entity {
    fn to() -> RelationDef {
        super::feed_category::Relation::Feed.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::feed_category::Relation::Category.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
