//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "category"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: Uuid,
    pub human_name: String,
    pub model_description: String,
    pub human_description: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    HumanName,
    ModelDescription,
    HumanDescription,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    ArticleData,
    FeedCategory,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Uuid.def(),
            Self::HumanName => ColumnType::String(StringLen::None).def(),
            Self::ModelDescription => ColumnType::String(StringLen::None).def(),
            Self::HumanDescription => ColumnType::String(StringLen::None).def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::ArticleData => Entity::has_many(super::article_data::Entity).into(),
            Self::FeedCategory => Entity::has_many(super::feed_category::Entity).into(),
        }
    }
}

impl Related<super::article_data::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArticleData.def()
    }
}

impl Related<super::feed_category::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FeedCategory.def()
    }
}

impl Related<super::feed::Entity> for Entity {
    fn to() -> RelationDef {
        super::feed_category::Relation::Feed.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::feed_category::Relation::Category.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
