//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude;

pub mod article;
pub mod article_data;
pub mod category;
pub mod feed;
pub mod feed_category;
pub mod sea_orm_active_enums;
pub mod user;
pub mod user_feed_favorite;
