//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "article_status")]
pub enum ArticleStatus {
    #[sea_orm(string_value = "pending")]
    Pending,
    #[sea_orm(string_value = "extracted")]
    Extracted,
    #[sea_orm(string_value = "extraction_failed")]
    ExtractionFailed,
    #[sea_orm(string_value = "done")]
    Done,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "feed_type")]
pub enum FeedType {
    #[sea_orm(string_value = "rss")]
    Rss,
}
