//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "user_feed_favorite")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_uuid: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub feed_uuid: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::feed::Entity",
        from = "Column::FeedUuid",
        to = "super::feed::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Feed,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserUuid",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::feed::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Feed.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
