//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub email: String,
    #[sea_orm(unique)]
    pub username: String,
    pub is_admin: bool,
    pub can_create_feeds: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::feed::Entity")]
    Feed,
    #[sea_orm(has_many = "super::user_feed_favorite::Entity")]
    UserFeedFavorite,
}

impl Related<super::user_feed_favorite::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserFeedFavorite.def()
    }
}

impl Related<super::feed::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_feed_favorite::Relation::Feed.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_feed_favorite::Relation::User.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
